---
title: "Make figures for manuscript"
output: html_document
date: "2025-10-10"
---

# Summary

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(terra)
library(foreach)
library(doParallel)
library(glue)
library(qs)
library(here)
library(countrycode)
library(strex)
library(data.table)
library(scales)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(viridis)


source(here("R/dir.R"))


data_grid <- data.table::fread(here::here("data/model_features/global_grid.csv")) %>%
  st_drop_geometry %>%
  dplyr::select(lon, lat, pixel_id)
```

Lets compare our artisanal modelling to Rousseau et al. artisanal data 

```{r}
saup_codes <- read.csv("https://data.imas.utas.edu.au/attachments/1241a51d-c8c2-4432-aa68-3d2bae142794/SAUPtoCountry.csv")

# lets load in the mapped artisanal powered and unpowered and join
options(timeout = 600)  # extend timeout to 10 minutes

mapped_2017_apw <- fread("https://data.imas.utas.edu.au/attachments/1241a51d-c8c2-4432-aa68-3d2bae142794/effort_mapped/mapped_2017_APW.csv")

mapped_2017_up <- fread("https://data.imas.utas.edu.au/attachments/1241a51d-c8c2-4432-aa68-3d2bae142794/effort_mapped/mapped_2017_UP.csv")

all_rousseau_2017 <- rbind(mapped_2017_apw, mapped_2017_up)

  all_files_flag <- list.files(file.path(rdsi_dir, "prep/random_forest/zenodo_data/artisanal_skylight_sentinel/mapped_by_flag_country/"), full.names = TRUE)

    all_data <- lapply(all_files_flag, fread) %>%
      bind_rows()
    
    all_data_2017 <- all_data %>%
      filter(year == 2017)
    
test_new <- all_data_2017 %>%    
      group_by(lon, lat) %>%
      summarise(effort = sum(nom_active_fishing_hours, na.rm = TRUE)) %>%
      ungroup() %>%
      filter(effort > 0) %>%
      rast(., type = "xyz")
    
    
test_rousseau <- all_rousseau_2017 %>%
  group_by(Lon, Lat) %>%
  summarise(nom_eff = sum(NomActive, na.rm = TRUE)) %>%
  ungroup() %>%
  na.omit() %>%
  filter(nom_eff > 0) %>%
  rast(., type = "xyz")


par(mfrow = c(2, 1))  # 2 rows, 1 column
plot(test_new, main = "Predicted effort (new model)")
plot(test_rousseau, main = "Rousseau et al. 2019 effort")

# interesting, looks pretty similar, however, ours is definitely 1) more concentrated, and 2) closer to shore. I am a little confused because presumably Watson (and by extension Rousseau) have the same <=50km or >=200m depth as us, but it looks like their artisanal goes out to the edge of EEZs (very low effort all the way out on the edge though). Just looking at unpowered looks a lot more similar.

```

Now compare to Watson since that looked like not what we would expect

```{r}
# catch <- fread(file.path(rdsi_raw_dir, "fishing_effort_catch_from_gem/catch_histsoc_1869_2017_EEZ_addFAO.csv")) # not this

catch <- fread(file.path("/home/ubuntu/gem/private/users/yannickr/Reg_catchData/20220606_RegCatchData/NonHistoricalNIndCami.csv"))

    
test_catch <- catch %>%
  filter(Year == 2017) %>%
  mutate(catch_t = Reported + IUU + Discards) %>%
  group_by(Lon, Lat) %>%
  summarise(catch_t = sum(catch_t, na.rm = TRUE)) %>%
  ungroup() %>%
  na.omit() %>%
  filter(catch_t > 0) %>%
  rast(., type = "xyz")

plot(test_catch, col = "red")
# ok this looks more appropriate, aside from some random stuff in the atlantic and the east coast of south america seemlingly missing...

    
test_catch_2 <- catch %>%
  filter(Year == 2017) %>%
  mutate(catch_t = Reported + IUU + Discards) %>%
  group_by(Lon, Lat) %>%
  summarise(catch_t = sum(catch_t, na.rm = TRUE)) %>%
  ungroup() %>%
  na.omit() %>%
  filter(catch_t > 0) %>%
  mutate(catch_pres = 1)


p1 <- ggplot(test_catch_2) +
  geom_raster(aes(x = Lon, y = Lat, fill = catch_pres)) +
  coord_equal() +
  # scale_fill_manual(
  #   name = "Catch presence",
  #   values = c("No catch" = "grey85", "catch" = "#1b9e77"),
  #   drop = FALSE
  # ) +
  labs(
    x = "Catch presence",
    y = ""
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text = element_text(size = 10),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

# compare to our IFA layer


ifa_fin_fin <- qs::qread(here("data/model_features/ifa/ifa_fin.qs"))

# cool! 

test_df <- ifa_fin_fin %>% 
  filter(year == 2017) %>%
  select(lon, lat, ifa) %>%
  mutate(ifa = factor(ifa, levels = c(0, 1), labels = c("No IFA", "IFA")))

p2 <- ggplot(test_df) +
  geom_raster(aes(x = lon, y = lat, fill = ifa)) +
  coord_equal() +
  scale_fill_manual(
    name = "IFA status",
    values = c("No IFA" = "grey85", "IFA" = "#1b9e77"),
    drop = FALSE
  ) +
  labs(
    x = "Inshore fishing areas",
    y = ""
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text = element_text(size = 10),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

library(patchwork)

p1/p2

## looks pretty ok, except for some areas like West Africa or Indonesia appear a bit more off the coast than ours? Otherwise I feel pretty confident that our IFA is likely more correct. I've checked multiple times that our operations were successful and good, so i think it is ok. 
```

