---
title: "Prep gfw fishing effort to feed to model for 0.5 degree"
output: html_document
date: "2025-07-23"
---

# Summary

Here we combine the data created in the previous files/folders so that we can feed it into a prediction model. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(qs)
library(here)
library(glue)
library(janitor)

source(here("R/dir.R"))
grid <- read.csv(here("data/model_features/global_grid.csv"))

```

```{r}


  # Load effort proportions
  effort_props <- qread(here("data/vessels/vessels_prop_05_deg_sentinel.qs")) %>%
    filter(nv > 0)

  # Load effort proportions
  effort_props_2 <- qread(here("data/vessels/vessels_prop_05_deg_skylight.qs")) %>%
    filter(nv > 0)

  
  # Combine all data
  year_data <- effort_props %>%
    rbind(effort_props_2) %>%
    mutate(sector = "Artisanal") %>% 
    dplyr::group_by(
      pixel_id, lon, lat,
      flag_fin, length_category,
      year
    ) %>%
    summarise(nv = sum(nv, na.rm = TRUE)) %>%
    ungroup() %>%
    group_by(flag_fin, year, length_category) %>%
    mutate(total_nv = sum(nv)) %>%
    ungroup() %>%
    mutate(prop_vessels = nv/total_nv)

  
# Save prepared data
saveRDS(year_data, here("data/model_features/prepared_data_0.5_all_skylight_sentinel.rds"))

```

Also prep the Rousseau data for eventual predictions
We need to prep Rousseau data by calculating average gross tonnage and Days at sea per flag and length combinations. Using these metrics with the number of vessels, we can calculate effort. 

```{r}
rousseau_eff <- read.csv("https://data.imas.utas.edu.au/attachments/1241a51d-c8c2-4432-aa68-3d2bae142794/TotalEffortby_FishingCountry_LengthBoat_Gear_Sector.csv") %>%
  filter(!is.na(Length_Category)) %>%
  dplyr::select(-X) %>%
  clean_names() %>%
  filter(sector != "I") %>%
  group_by(flag_fin = country, length_category, year) %>%
  summarise(nom_active_days = sum(nom_active, na.rm = TRUE),
            eff_active_days = sum(eff_active, na.rm = TRUE), 
            nv = sum(nv, na.rm = TRUE),
            p = sum(p),
            gt = sum(gt)) %>%
  ungroup() %>%
  filter(nv > 0) %>%
  mutate(days_at_sea = nom_active_days/p,
         mean_engine_p = p/nv) 

qs::qsave(rousseau_eff, here("data/model_features/rousseau_total_art_vessels.qs"))

```
